# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 073f1d0526049f84a06e8e663dcb1ebf69abc8963e957ddc1dbc85afb42cd5d79f8d855a336c708adc7ca9926ee82f2a836d7dc692840e56c3317c3c6ebafa39

test:
  secret_key_base: feae4c22cb0f87287236e1b1f123dab8065cfc9907ea9b907ec4976bce5943f8ca9a0eb6bb7e0b525359b20dbff418d13ee70a31e2c9585d8c675581ae1040b8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
